apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-6suk
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0075-tenant/tkrw-pr712-0075-0075-app/devfile-sample-6suk@sha256:5cefa59e1df4ffa019f7617f58fe6cef4232e23386a45ff35357685438f1929a
        name: my-nodejs
        resources: {}
status: {}
